pekko {
  loglevel = debug

  actor {
    provider = cluster
    serialization-bindings {
      "cluster.CborSerializable" = jackson-cbor
    }
  }

  remote.artery {
    transport = tcp
    canonical.hostname = "127.0.0.1"
    canonical.port = 0
  }

  cluster {
    seed-nodes = [
      "pekko://ClusterSystem@127.0.0.1:2551",
      "pekko://ClusterSystem@127.0.0.1:2552"
    ]

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    split-brain-resolver {
        active-strategy = keep-majority
    }
  }
}